// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.md" {
  const markdown: string;
  export default markdown;
  export const meta: Record<string, string>
}
